"""Featured AI source navigation data for V0.3 UI."""

FEATURED_SOURCES = [
    # P0 — Must watch
    {
        "source_key": "openai_news",
        "name": "OpenAI",
        "display_name": "OpenAI",
        "icon": "🧠",
        "category": "company",
        "priority": "P0",
        "homepage_url": "https://openai.com/news/",
        "focus": "模型、Agent、开发者工具",
        "why": "直接反映 OpenAI 前沿模型和产品方向。",
        "tags": ["模型", "Agent", "开发者工具"],
    },
    {
        "source_key": "anthropic_news",
        "name": "Anthropic News",
        "display_name": "Anthropic",
        "icon": "🟣",
        "category": "company",
        "priority": "P0",
        "homepage_url": "https://www.anthropic.com/news",
        "focus": "Claude、AI Safety、Agent、企业应用",
        "why": "直接反映 Anthropic 前沿模型和 AI Safety 方向。",
        "tags": ["Claude", "AI Safety", "Agent"],
    },
    {
        "source_key": "deepmind_blog",
        "name": "Google DeepMind Blog",
        "display_name": "DeepMind",
        "icon": "🔬",
        "category": "research",
        "priority": "P0",
        "homepage_url": "https://deepmind.google/discover/blog/",
        "focus": "Gemini、多模态、AI for Science",
        "why": "DeepMind 是最具影响力的 AI 研究机构之一。",
        "tags": ["Gemini", "多模态", "研究"],
    },
    {
        "source_key": "huggingface_blog",
        "name": "Hugging Face Blog",
        "display_name": "Hugging Face",
        "icon": "🤗",
        "category": "open_source",
        "priority": "P0",
        "homepage_url": "https://huggingface.co/blog",
        "focus": "开源模型、Transformers、State-of-the-Art",
        "why": "Hugging Face 是开源 AI 生态核心，直接反映开源模型前沿。",
        "tags": ["开源模型", "Transformers", "社区"],
    },
    {
        "source_key": "arxiv_cs_ai",
        "name": "arXiv cs.AI",
        "display_name": "arXiv AI",
        "icon": "📄",
        "category": "paper",
        "priority": "P0",
        "homepage_url": "https://arxiv.org/list/cs.AI/recent",
        "focus": "Agent、推理、RAG、AI Safety 论文",
        "why": "arXiv 是 AI 前沿研究的第一手发布渠道。",
        "tags": ["论文", "Agent", "推理", "RAG"],
    },
    {
        "source_key": "nvidia_ai_blog",
        "name": "NVIDIA AI Blog",
        "display_name": "NVIDIA AI",
        "icon": "🟩",
        "category": "company",
        "priority": "P0",
        "homepage_url": "https://blogs.nvidia.com/blog/category/generative-ai/",
        "focus": "Agentic AI、Physical AI、GPU、机器人、开发者工具",
        "why": "NVIDIA AI 博客覆盖 agentic AI、physical AI、RTX/DGX/Jetson 等方向。",
        "tags": ["NVIDIA", "GPU", "Agent", "物理AI"],
    },
    # P1 — High value
    {
        "source_key": "meta_ai_blog",
        "name": "Meta AI Blog",
        "display_name": "Meta AI",
        "icon": "🧩",
        "category": "company",
        "priority": "P1",
        "homepage_url": "https://ai.meta.com/blog/",
        "focus": "开源模型（LLaMA）、多模态、Agents",
        "why": "Meta AI 直接反映开源模型和多模态研究前沿。",
        "tags": ["开源模型", "多模态", "LLaMA"],
    },
    {
        "source_key": "microsoft_ai_source",
        "name": "Microsoft AI Source",
        "display_name": "Microsoft AI",
        "icon": "🪟",
        "category": "company",
        "priority": "P1",
        "homepage_url": "https://news.microsoft.com/source/topics/ai/",
        "focus": "Copilot、Azure AI、企业 AI、AI agent",
        "why": "Microsoft AI Source 是微软 AI / Copilot / enterprise AI 的官方聚合入口。",
        "tags": ["Microsoft", "Copilot", "Azure AI", "企业AI"],
    },
    {
        "source_key": "stanford_hai",
        "name": "Stanford HAI",
        "display_name": "Stanford HAI",
        "icon": "🏛️",
        "category": "research",
        "priority": "P1",
        "homepage_url": "https://hai.stanford.edu/news",
        "focus": "AI 政策、AI 社会影响、人机交互",
        "why": "Stanford HAI 聚焦 AI 与社会的交叉方向。",
        "tags": ["Stanford", "AI政策", "人机交互"],
    },
    {
        "source_key": "mit_news_ai",
        "name": "MIT News AI",
        "display_name": "MIT AI",
        "icon": "🧪",
        "category": "research",
        "priority": "P1",
        "homepage_url": "https://news.mit.edu/topic/artificial-intelligence-0807",
        "focus": "AI 机器人研究、AI 政策、AI 安全",
        "why": "MIT AI 新闻覆盖机器人、AI 政策与安全的前沿报道。",
        "tags": ["MIT", "机器人", "AI安全"],
    },
    {
        "source_key": "berkeley_bair_blog",
        "name": "Berkeley BAIR Blog",
        "display_name": "Berkeley BAIR",
        "icon": "🐻",
        "category": "research",
        "priority": "P1",
        "homepage_url": "https://bair.berkeley.edu/blog/",
        "focus": "推理、机器人、世界模型、RL、AI 安全",
        "why": "BAIR Blog 有 Berkeley AI 研究更新，覆盖推理和机器人等前沿方向。",
        "tags": ["Berkeley", "推理", "机器人", "世界模型"],
    },
    {
        "source_key": "mistral_ai_news",
        "name": "Mistral AI News",
        "display_name": "Mistral AI",
        "icon": "🌬️",
        "category": "company",
        "priority": "P1",
        "homepage_url": "https://mistral.ai/news/",
        "focus": "开源模型、企业 LLM、欧洲 AI 生态",
        "why": "Mistral 是重要模型公司来源，反映开源和欧洲 AI 前沿。",
        "tags": ["Mistral", "开源模型", "LLM"],
    },
    {
        "source_key": "cohere_blog",
        "name": "Cohere Blog",
        "display_name": "Cohere",
        "icon": "🔎",
        "category": "company",
        "priority": "P1",
        "homepage_url": "https://cohere.com/blog",
        "focus": "企业 LLM、RAG、检索、Command 模型",
        "why": "Cohere 是重要模型公司，RAG 和企业应用方向具有参考价值。",
        "tags": ["Cohere", "RAG", "企业LLM"],
    },
    # arXiv supplemental — cs.CL and cs.LG
    {
        "source_key": "arxiv_cs_cl",
        "name": "arXiv cs.CL",
        "display_name": "arXiv NLP",
        "icon": "📄",
        "category": "paper",
        "priority": "P2",
        "homepage_url": "https://arxiv.org/list/cs.CL/recent",
        "focus": "大语言模型、NLP 架构、推理优化",
        "why": "cs.CL 是 NLP 研究的第一手来源。",
        "tags": ["NLP", "LLM", "论文"],
    },
    {
        "source_key": "arxiv_cs_lg",
        "name": "arXiv cs.LG",
        "display_name": "arXiv ML",
        "icon": "📄",
        "category": "paper",
        "priority": "P2",
        "homepage_url": "https://arxiv.org/list/cs.LG/recent",
        "focus": "深度学习理论、训练方法、优化算法",
        "why": "cs.LG 是机器学习理论研究的核心来源。",
        "tags": ["机器学习", "理论", "论文"],
    },
]


def get_featured_sources() -> list[dict]:
    """Return the featured AI source list for UI rendering."""
    return FEATURED_SOURCES
